<div class="article">
	
	<h2>Article 1</h2>
	
	<br/>Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
	<br/>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
	<br/>when an unknown printer took a galley of type and scrambled it to make a type
	<br/>specimen book. It has survived not only five centuries, but also the leap into
	<br/>electronic typesetting, remaining essentially unchanged. It was popularised in 
	<br/>the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
	<br/>and more recently with desktop publishing software like Aldus PageMaker including
	<br/>versions of Lorem Ipsum.	
		
</div>



