<?php 
//on récupére l'instance de zend_auth
$auth = Zend_Auth::getInstance();

if ($auth->hasIdentity())
{?>
	<div class = "listegauche">
<?php
}
else
{?>
	<div class = "listedroite">
<?php 
}?>

<h2><U>Article(s)</U></h2>

<?php 
		$lesArticles = $this->lesArticles; 
	  	foreach($lesArticles as $unArticle) 
	  	{ 
	  		if ($auth->hasIdentity())
	  		{?>
	  						  		
		  		<a 
		  			href="<?php echo $this->baseUrl('articles/afficherarticleselect')."?idArticle=$unArticle->id" ?>">
					Numero de l'article : <?php echo $unArticle->id;?>
				</a><br/>
				
				<U>Date :</U> <?php echo $unArticle->date; ?><br/>		
				<U>Titre :</U> <?php echo $unArticle->titre;?><br/>		
		
			  	<a 
		  			href="<?php echo $this->baseUrl('articles/supprimerarticle')."?idArticle=$unArticle->id" ?>">
					Supprimmer<br/>
				</a>
				<a 
		  			href="<?php echo $this->baseUrl('articles/modifierarticle')."?idArticle=$unArticle->id" ?>">
					Modifier<br/>
				</a>					
		  						
					___________________
      <?php }
      		else 
			{
				if($unArticle->publication == 1)
				{?>
				<a
					href="<?php echo $this->baseUrl('articles/afficherarticleselect')."?idArticle=$unArticle->id" ?>">
					<?php echo $unArticle->date; ?><br/>
				</a>																
				<?php echo $unArticle->titre;
				}
			}
			?>
	  								   
  <?php } ?>
	 
</div>
