<div class = "article">
<?php 
$affichage = $this->affichage;
$compteur = $this->compteur;
$listeArticle = $this->listeArticle;
$listeCom = $this->listeCom;
$count = count($listeCom);
?>

<table border="1">
	<tr>
		<td><?php echo $listeArticle[1][0];?></td>
	</tr>
	<tr>
		<td><?php echo $listeArticle[1][1];?></td>
	</tr>
</table>
</div>
<br/><br/><br/>

<div class = "commentaire">
	<?php 
	for ($i = 1; $i <= $count; $i++) {
	?>

				<?php echo $listeCom[$i][0]; ?> <br />
				<?php echo $listeCom[$i][1]; ?> <br />
	<?php
	}
	?>
</div>
<br/><br/><br/>
