<h1>Articles</h1>

<ul>
	<li>
		<a href="<?php echo $this->baseUrl('articles/index'); ?>?valeur=afficherarticle">
			Liste des articles
		</a>
	</li>
	<li>
		<a href="<?php echo $this->baseUrl('articles/index'); ?>?valeur=ajoutarticle">
			Ajout des articles
		</a>
	</li>		
</ul>

<h1>Commentaire</h1>

<ul>
	<li>
		<a href="<?php echo $this->baseUrl('articles/index'); ?>?valeur=affichercommentaire">
			Liste des commentaires
		</a>
	</li>
	<li>
		<a href="<?php echo $this->baseUrl('articles/index'); ?>?valeur=ajoutcommentaire">
			Ajout des commentaires
		</a>
	</li>		
</ul>