<div class = "commentaire">
<h2><U>Commentaire(s)</U></h2>
<?php
		$lesCommentaires = $this->lesCommentaires;
		foreach($lesCommentaires as $unCommentaire)
		{ ?>
			<U>Numéro de l'article :</U> <?php echo $unCommentaire->idArticle;?><br/>	
			<U>Date :</U> <?php echo $unCommentaire->date;?><br/>				
			<U>Auteur :</U> <?php echo $unCommentaire->auteur; ?><br/><br/>	
			<U>Commentaire :</U><br> <?php echo $unCommentaire->commentaire; ?><br/>	<br/>
			<a 
	  			href="<?php echo $this->baseUrl('commentaire/modifierlecommentaire')."?idCommentaire=$unCommentaire->id" ?>">
	  			Modifier	
	  		</a><br>
	  		<a 
	  			href="<?php echo $this->baseUrl('commentaire/supprimercommentaire')."?idCommentaire=$unCommentaire->id" ?>">
	  			Supprimer	
	  		</a><br/>
				
<?php  } ?>

</div>
