<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Blog</title>	
	<link href="<?php echo $this->baseUrl('/css/style.css')?>" media="screen" rel="stylesheet" type="text/css" />
	<?php   
		$this->jQuery()->enable();
		echo $this->jQuery();
	?>
	
	
</head>

<body>
	
	
	<div class="connexion">
			<?php 
				echo $this->action('login', 'index');
			?>
	</div>

	
	<div id="entete">
		<h1><a href="/">Blog</a></h1>		
	</div>
	
	<?php 
		
		//on récupére l'instance de zend_auth
    	$auth = Zend_Auth::getInstance();
    	
    	//on verifie si l'utilisateur est connecté
    	if ($auth->hasIdentity())
		{?>
		<div class="menu">
			<?php  echo $this->layout()->menu; ?>			
		</div>	
	<?php }?> 
	
	<div id="contenu">
		<?php echo $this->layout()->content; ?>
	</div>
	
</body>

<footer>
	<div id="pied">
		<p id="copyright">Cyril DOYEN &copy; 2012</p>
	</div>	
</footer>

</html>
